### ISSUE TITLE
UnhandledPromiseRejectionWarning:

### ISSUE THREAD

**Issue by wuast94** [smartcuc/COVID-19#28]
I use the German js file and added user and password .. before and after that i get the same error: 

```
node app.js                                                                                                                                                                                                  
(node:56856) UnhandledPromiseRejectionWarning: Error: No node found for selector: .fnktable__expand
    at Object.exports.assert (/home/wuast94/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
    at DOMWorld.click (/home/wuast94/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:277:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async scraeData (/home/wuast94/Documents/covidapp/app.js:54:5)
    at async getCovidGerman (/home/wuast94/Documents/covidapp/app.js:187:20)
(node:56856) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:56856) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Seems that this not stop the process but i dont see any values in my db

**Comment by ramoneich** [comment]
Hello

update of data stoppt working with the following error: **(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object**

`(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at getCountryData (/work/appNew.js:184:37)
    at Covid (/work/appNew.js:241:29)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
`

**Comment by karlzre** [comment]
Hi, 
I get the same here :

` node appNew.js
2021-02-05 11:00:17 - Running update
(node:2947) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at getCountryData (/home/administrateur/COVID-19/appNew.js:184:37)
    at Covid (/home/administrateur/COVID-19/appNew.js:241:29)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:2947) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2947) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
administrateur@administrateur-iMac:~/COVID-19$
`

**Comment by ramoneich** [comment]
Hello, just want to know if anybody has it working again. The appnew.js was updated 11 days ago. But the same error appears. If you have an alternative @karlzre or @wuast94 for getting covid data in an influxdb I would be very happy. Thanks

**Comment by karlzre** [comment]
@ramoneich just updated and still the same issue here.

**Comment by smartcuc** [comment]
Well, my dev-pc has broken. Need to get a new one to move forward.
