### ISSUE TITLE
Dockerfile missing https-proxy-agent (couldn't get it to work anyways)

### ISSUE THREAD

**Issue by maglub** [smartcuc/COVID-19#8]
Hi,

Thanks for the good work! Love it!

The Dockerfile is missing ```npm install https-proxy-agent```, but even after adding it, I could not get the app.js to work with it. My workaround at the moment is to disable the proxy agent part completely.

# Dockerfile fix

```
ops@com-docker-l01a:~/COVID-19$ git diff Dockerfile
diff --git a/Dockerfile b/Dockerfile
index f8374d9..98c9c16 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -6,6 +6,6 @@ RUN apt-get update && \
 WORKDIR /work
 
 ADD . /work/
-RUN npm install papaparse influx axios
+RUN npm install papaparse influx axios https-proxy-agent
 
 ENTRYPOINT ["node", "/work/app.js"]
```

```
ops@com-docker-l01a:~/COVID-19$ docker build -t corona .

ops@com-docker-l01a:~/COVID-19$ docker run -e INFLUX_HOST=192.168.4.55 -it corona
(node:1) UnhandledPromiseRejectionWarning: Error: Request failed with status code 500
    at createError (/work/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/work/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/work/node_modules/axios/lib/adapters/http.js:236:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

# Workaround

```
ops@com-docker-l01a:~/COVID-19$ git diff app.js
diff --git a/app.js b/app.js
index 539051f..391cfa7 100644
--- a/app.js
+++ b/app.js
@@ -2,10 +2,12 @@ const papa = require('papaparse');
 const influx = require('influx');
 const axios = require('axios');
 const HttpsProxyAgent = require('https-proxy-agent');
-const axiosDefaultConfig = {
-    proxy: false,
-    httpsAgent: new HttpsProxyAgent('http://XXXX:XXXX@XXXX:XXXX')
-};
+//const axiosDefaultConfig = { 
+//    proxy: false,
+//    httpsAgent: new HttpsProxyAgent('http://XXXX:XXXX@XXXX:XXXX')
+//};
+
+const axiosDefaultConfig = { }
 
 // Get INFLUX_HOST environment variable
 const influxhost = process.env.INFLUX_HOST;
```

**Comment by smartcuc** [comment]
Well, as I do nit use docker, I cannot fix that issue.

**Comment by maglub** [comment]
The first issue with Docker is fixed by adding the line as above in the ```diff Docker```, easy fix.

But for the proxy config, I think it does not follow the syntax of the axios config. Should give the same issue even if you don't run it in docker.

**Comment by smartcuc** [comment]
appNew.js has been uploaded.

**Comment by maglub** [comment]
Thanks
